---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-istio-base
  namespace: flux-system
spec:
  targetNamespace: istio-system
  path: ./k8s/apps/istio-system/istio/base
  prune: true
  sourceRef:
    kind: GitRepository
    name: zhopp-k8s
  wait: true
  postBuild:
    substituteFrom: []
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  dependsOn:
    - name: cluster-apps-kube-prometheus-stack-crds
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-istiod
  namespace: flux-system
spec:
  targetNamespace: istio-system
  path: ./k8s/apps/istio-system/istio/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: zhopp-k8s
  wait: true
  postBuild:
    substituteFrom: []
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  dependsOn:
    - name: cluster-apps-istio-base
