---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-kyverno
  namespace: flux-system
spec:
  targetNamespace: kyverno
  path: "./k8s/apps/kyverno/kyverno/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: zhopp-k8s
  wait: true
  interval: 30m
  timeout: 5m
  retryInterval: 1m
  postBuild:
    substituteFrom: []
  dependsOn:
    - name: cluster-apps-kube-prometheus-stack-crds
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-cluster-policies
  namespace: flux-system
spec:
  targetNamespace: kyverno
  path: ./k8s/apps/policy/kyverno/policies
  prune: true
  sourceRef:
    kind: GitRepository
    name: zhopp-k8s
  wait: false # no flux ks dependents
  postBuild:
    substituteFrom: []
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  dependsOn:
    - name: cluster-apps-kyverno
