---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: zhopp-k8s
  namespace: flux-system
spec:
  interval: 30m
  ref:
    branch: main
  url: https://github.com/zhopp/homeops
  ignore: |
    # exclude all
    /*
    # include k8s directory
    !/k8s/
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster
  namespace: flux-system
spec:
  interval: 10m
  path: ./k8s/flux
  prune: true
  wait: false
  sourceRef:
    kind: GitRepository
    name: zhopp-k8s
  dependsOn:
    - name: flux
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-settings
        optional: false
      - kind: Secret
        name: cluster-secrets
        optional: false
