---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-kube-prometheus-stack-crds
  namespace: flux-system
spec:
  targetNamespace: monitoring
  path: ./k8s/apps/monitoring/kube-prometheus-stack/crds
  prune: true
  sourceRef:
    kind: GitRepository
    name: zhopp-k8s
  wait: true
  postBuild:
    substituteFrom: []
  interval: 30m
  retryInterval: 1m
  timeout: 5m
