apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-cloudnative-pg
  namespace: flux-system
spec:
  targetNamespace: cnpg
  path: ./k8s/apps/cnpg/cloudnative-pg/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: zhopp-k8s
  wait: true
  postBuild:
    substituteFrom: []
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  dependsOn:
    - name: cluster-apps-istiod
