---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-rook-ceph-operator
  namespace: flux-system
spec:
  targetNamespace: storage
  interval: 10m
  path: "./k8s/apps/storage/rook-ceph/operator"
  prune: true
  sourceRef:
    kind: GitRepository
    name: zhopp-k8s
  wait: true
  postBuild:
    substituteFrom: []
  dependsOn:
    - name: cluster-apps-kube-prometheus-stack-crds
    - name: cluster-apps-snapshot-controller
    - name: cluster-apps-istiod
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-rook-ceph-cluster
  namespace: flux-system
spec:
  targetNamespace: storage
  interval: 10m
  path: "./k8s/apps/storage/rook-ceph/cluster"
  prune: true
  sourceRef:
    kind: GitRepository
    name: zhopp-k8s
  wait: true
  postBuild:
    substituteFrom: []
  dependsOn:
    - name: cluster-apps-rook-ceph-operator
