---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: cilium
  namespace: kube-system
spec:
  chart:
    spec:
      chart: cilium
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: cilium
        namespace: flux-system
      version: 1.15.6
  interval: 30m

  valuesFrom:
    - kind: ConfigMap
      name: cilium-values

  values:
    hubble:
      enabled: true
      metrics:
        enabled:
          - dns:query;ignoreAAAA
          - drop
          - tcp
          - flow
          - port-distribution
          - icmp
          - http
      ui:
        enabled: true
        rollOutPods: true
      relay:
        enabled: true
        rollOutPods: true
