---
apiVersion: cilium.io/v2alpha1
kind: CiliumL2AnnouncementPolicy
metadata:
  name: policy
spec:
  loadBalancerIPs: true
  interfaces: ["^eth.*"]
  nodeSelector:
    matchLabels:
      kubernetes.io/os: linux
---
apiVersion: "cilium.io/v2alpha1"
kind: CiliumLoadBalancerIPPool
metadata:
  name: "ip-pool"
spec:
  blocks:
  - cidr: "192.168.4.252/30"
---
