---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-cilium
  namespace: flux-system
spec:
  targetNamespace: kube-system
  path: "./k8s/apps/kube-system/cilium/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: zhopp-k8s
  wait: true
  interval: 30m
  timeout: 5m
  retryInterval: 1m
  postBuild:
    substituteFrom: []
