---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-reloader
  namespace: flux-system
spec:
  targetNamespace: system
  interval: 10m
  path: "./k8s/apps/system/reloader/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: zhopp-k8s
  wait: true
  postBuild:
    substituteFrom: []
  dependsOn:
    - name: cluster-apps-kube-prometheus-stack-crds
