---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istiod
spec:
  interval: 30m
  chart:
    spec:
      chart: istiod
      version: 1.22.3
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system
      interval: 30m
  values:
    defaults:
      sidecarInjectorWebhook:
        enableNamespacesByDefault: true
    pilot:
      env:
        ENABLE_NATIVE_SIDECARS: true
